version: '3'
services:
            
    db:
        image: mongo
        ports: 
        - "27017:27017"
        
    feed:
        build: './feed'
        ports: 
        - "5000:5000"
        depends_on:
        - post
        
    post:
        build: './post'
        ports:
        - "5001:5001"
        environment: 
        - MONGO_DB_URI_POST=mongodb://db:27017/Post
        links: 
        - db

    profile:
        build: './profile'
        ports: 
        - "5002:5002"
        environment: 
        - MONGO_DB_URI_PROFILE=mongodb://db:27017/Profile
        links: 
        - db

    search:
        build: './search'
        ports: 
        - "5003:5003"
        depends_on:
        - post
        - profile

            